### ISSUE TITLE
Installation process

### ISSUE THREAD

**Issue by barrydevt** [GlobalFreightSolutions/magento2-gfs#2]
Hi,

Tried `composer require justshout/magento2-gfs` but the package doesn't seem to be on packagist? 

Also tried to add via VCS, but the module does not seem to be version tagged? 

What is the correct way to install?

**Comment by mpachnis** [comment]
Hi barrydevt,

Currently there is only way to install the module, manually. 
Clone or download the project form here, upload the files into magentoRootDirecory/app/code/JustShout/Gfs.
Run the upgrade command with `php magento setup:upgrade`

The module should be available on STORES > Settings > Configuration and then going to Sales > Shipping Methods there should be a new tab named 'GFS (Global Freight Solutions)'

Any issue, please let us know.
